### ISSUE TITLE
Edit the story details for seven functions

### ISSUE THREAD

**Issue by zzihan1203** [NYUDevops-ShopCart/shopcarts#10]
**As a** ...  
**I need** ...  
**So that** ...  

**Assumptions:** 
* ...

**Acceptance Criteria:**
```
Given ...
When ...
Then ...
```

**Comment by zzihan1203** [comment]
I think we should create and assign specific stories to each member. For example, I will create a story called "edit the details about #2 and #3" and assign it to myself. Then we will have one story assigned to each one and have 4 stories done for sprint 1. What do you think about this?

**Comment by zzihan1203** [comment]
I don't think we should set the sprint 1 as our milestone for our 7 API functions because we can't implement these functions in two weeks. And milestone is supposed to be finished by the end of this sprint. So more specific and appropriate stories for milestone 1 should be "edit the story about ......".

**Comment by zzihan1203** [comment]
And for the 7 stories we created to implement functions, we can leave them in the icebox and set the milestone for them in the future.

**Comment by zzihan1203** [comment]
I have studied about some materials and still think we shouldn't set the milestone sprint 1 for those 7 stories. Because once you set a milestone for them, you need to finish them in the end of this sprint and obviously we can't implement the functions in two weeks. That's not our goal. What we should do is to create new stories about editing and set the milestone sprint 1 for them.

**Comment by hh1834** [comment]
Should we move the 7 stories to milestone 2 and put them in the icebox? I think we were not supposed to have any items in the New Issues pipeline

**Comment by zzihan1203** [comment]
I talked to our professor about the requirements of the functions about shopcart.
list: all items in our shopcart
read: one item(id, name, price, quantity) Notice that the id is the only attribute that has to be as same as the product team.
create: create a shopcart at the beginning; add new items to an existing shopcart
update: update the quantity or the price based on our database
delete: delete an item from the shopcart
query: the background is one shopcart. ex: list all items which is more expensive than 5$
perform: check out
