### ISSUE TITLE
Decide What Database to Use

### ISSUE THREAD

**Issue by hh1834** [NYUDevops-ShopCart/shopcarts#14]
**As a** developer
**I need** a database
**So that** shop cart items and quantities can be stored with an unique id

**Assumptions:** 
* Relational database
* MySQL

**Acceptance Criteria:**
```
Given I have the database
When I store a user id and cart data
Then I should have the id and data stored in our database
```

**Comment by hh1834** [comment]
I read the homework description and it seems we can use either relational / non-relational database we like. I personally like NoSQL because it is much more scalable and generally I think of number of user ids increasing like crazy if a shopping website becomes a success like Amazon.

**Comment by zzihan1203** [comment]
I talked to the professor after class. And he said that we can use our own database as long as we have the matched id with product teams & customer teams. And there is only one table, which stores the item id as the primary key(simpler), customer id, name, quantity, price.

**Comment by ytc338** [comment]
Our database contains only one table
columns are
- id(primary key, auto generated)
- item id
- customer id
- quantity
- price
- state

Let's just go with MySQL because there are a lot of resource about how to set up MySQL in a Vagrantfile

**Comment by zzihan1203** [comment]
Agreed.

**Comment by hh1834** [comment]
Sounds good. Relational database it is then.
