### ISSUE TITLE
Create a Mysql Shopcart database

### ISSUE THREAD

**Issue by rishabhydv** [NYUDevops-ShopCart/shopcarts#15]
**As a** developer
**I need** a database
**So that** shop cart items and quantities can be stored with an unique id

**Schema**
```
id - auto increment
product_id - from the product API
customer_id - from the customer API
quantity - quantity of the items
price - per item
text - description
state - added, removed, done
```

**Assumptions:** 
Relational database are more suited for this use case.

**Acceptance Criteria:**
```
Given shopcart details
When a user add products to card
Then persist the data onto the database.
```

**Comment by rishabhydv** [comment]
I've made the changes for the database so go please go through the pull request and merge it.
Important changes:
1. Since there are changes in the provisions and requirements.txt file after you do vagrant up, please do vagrant provision so that the changes are reflected.

2. A mysql database will created with database name shopcarts whenever the vagrant environment is brought up
3. To access the mysql cli from inside the vagrant box please use the following command
docker exec -t -i mysql /bin/bash -c "mysql -uroot -ppassword"
4. To run the flask app do the following steps:
-export FLASK_APP=service/__init__.py (Go to the vagrant directory- cd ../../vagrant)
-flask run --host=0.0.0.0
5. To test if the environment and the database is up and running you can hit the following endpoint:
http://0.0.0.0:5000/shopcart
Let me know if you hit into any trouble with this.

**Comment by ytc338** [comment]
4. Should be `export FLASK_APP=service` and then `flask run --host=0.0.0.0`
But there are some more problem:
The professor said the only command he'll run are `vagrant up` and `flask run` so:

-   Can't `cd ../../vagrant`. So we should map the host app directory to the `/home/vagrant` i.e. ' ~ ' directory 

-  Can't add `--host=0.0.0.0` option. So we should find another way to make the app run at the right port. [This might help](https://stackoverflow.com/a/26075543)

**Comment by rishabhydv** [comment]
So the main reason for doing --host=0.0.0.0 is so that the flask application can be accessed from all the networks i.e outside the vagrant environment. Flask run would only run the application on 127.0.0.1 in the vagrant environment. However, you need to provision it so that you can access it from outside the vagrant environment.

export FLASK_APP is the file in which you are initializing your flask application which in our case is __init__.py

**Comment by ytc338** [comment]
```
git clone your-repo
cd your-repo
vagrant up
vagrant ssh
cd /vagrant
nosetests
FLASK_APP=service:app flask run --host=0.0.0.0 --port=8080
```
The professor will run this. The app runs but I have a problem accessing our app in the browser http://localhost:8080
Others looks great!

**Comment by zzihan1203** [comment]
I think the port should be 5000 based on the description about hw1 - part2, but we can always change that later.
