### ISSUE TITLE
API to list all items the shopcart

### ISSUE THREAD

**Issue by rishabhydv** [NYUDevops-ShopCart/shopcarts#2]
**As a** user:
**I need** to see the item names and quantities in my shopcart
**So that** a user can review items before continuing to check out

**Assumptions:** 
* should check with the Product and Customer team for the format of user ids
* will use relational / non-relational database to store user id and list of items

**Acceptance Criteria:**
```
When I add item X to a shop cart and use the list functionality
Then I should be able to see item X with quantity 1

pylint score must be at least 9.0/10.0
Following good REST API practices, your API should only return json (including error messages)
Logging is critical for debugging so make sure to log your actions
```

**Comment by hh1834** [comment]
I will be getting more clear grasp of what REST API is after today's class, but I tried editing the story thinking from the server's view of point in a client-server architecture
