### ISSUE TITLE
API to read details for a product in the customer shopcart

### ISSUE THREAD

**Issue by rishabhydv** [NYUDevops-ShopCart/shopcarts#3]
**As a** user
**I need** to read and fetch details of the product (id, name, price, quantity)
**So that** I can provide more details to the user

**Assumptions:** 
* The product id is shared by the product team
* The customer id is shared by the customer team

**Acceptance Criteria:**
```
Given I have customer shop cart information
When the customer clicks on a product
Then it should return the following details- id, name, price, quantity
```

**Comment by zzihan1203** [comment]
I think this is a user job.
