### ISSUE TITLE
Bug Report: Can't create shopcart item

### ISSUE THREAD

**Issue by hh1834** [NYUDevops-ShopCart/shopcarts#37]
**Describe the Problem**: when I call http://localhost:5000/shopcarts/1 with POST

**Describe what happened in as much detail as needed:** I expect 201 response code and item created

**Steps to Reproduce:**
1. vagrant up -> vagrant ssh -> run flask -> call http://localhost:5000/shopcarts/1 POST with Postman
...
...
**Expected Result:** get 201 response code 

**Tell us what you expected to happen**

**Observed Result:** 500 Internal Service Error 

**Tell us what you actually observed**

**Comment by ytc338** [comment]
Were you trying to create a item that is already in the cart for them same user?(known bug)
Or did you call with proper body?

**Comment by hh1834** [comment]
the problem has been fixed now
