### ISSUE TITLE
API to add a product in customer shopcart

### ISSUE THREAD

**Issue by rishabhydv** [NYUDevops-ShopCart/shopcarts#4]
**As a** user
**I need** to add the item I want with the quantity I want in my shopcart
**So that** I can eventually purchase the item

**Assumptions:** 
* should check with the Product and Customer team for the format of user ids
* will use relational / non-relational database to store user id and list of items

**Acceptance Criteria:**
```
When I add an item X with quantity 2 to a shopcart
Then my shopcart should contain item X with quantity 2 if it was not there before
If an item was already there quantity should increase

pylint score must be at least 9.0/10.0
Following good REST API practices, your API should only return json (including error messages)
Logging is critical for debugging so make sure to log your actions
```

**Comment by hh1834** [comment]
I will be getting more clear grasp of what REST API is after today's class, but I tried editing the story thinking from the server's view of point in a client-server architecture
