### ISSUE TITLE
API to query shopcart based on conditions

### ISSUE THREAD

**Issue by rishabhydv** [NYUDevops-ShopCart/shopcarts#7]
**As a** user
**I need** to view my shopcart based on certain conditions
**So that** I can view my cart based on certain filters

**Assumptions:** 
* The cart is not empty

**Acceptance Criteria:**
```
Given I have a non-empty shopcart
When I put some filter on my cart
Then I should be able to see products according to the filter
```

**Comment by zzihan1203** [comment]
I have tested this function on my laptop and it works. So I designed the query function like this: 
receive a customer id and a target price from the URL, return all items in the shop cart for this customer which has lower price than the target price.  
If you all agree with this design, you can test and merge.
