### ISSUE TITLE
API to move to checkout stage

### ISSUE THREAD

**Issue by rishabhydv** [NYUDevops-ShopCart/shopcarts#8]
**As a** user
**I need** to proceed to the next stage i.e checkout
**So that** I can confirm my order for the items on my shopcart.

**Assumptions:** 
* The cart is not empty.

**Acceptance Criteria:**
```
Given a non-empty cart
When I click to proceed
Then I should be able to proceed to the checkout stage to confirm the order.
```

**Comment by zzihan1203** [comment]
The professor said we can do the following things for the "action" requirement:
return the id of all items in the shopcart; 
delete the shopcart.

**Comment by zzihan1203** [comment]
We can if we want to call order API but that sounds a lot of work. So above is the simpler way to do.
